buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://clojars.org/repo" }
    }
}

ext {
    nanojsonVersion = "1d9e1aea9049fc9f85e68b43ba39fe7be1c1f751"
    spotbugsVersion = "4.10.2"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
